### ISSUE TITLE
Decompiling LuaJit Scripts from Farming Simulator 2015

### ISSUE THREAD

**Issue by Bluetiger** [NightNord/ljd#15]
Hello.

If tried to decompile bytecode files from FS15. But just getting any KeyError. Do you have any suggestion? 

Hopefully Blue

Text from Commandpromptscreen:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    retval = main()
  File "main.py", line 85, in main
    ast = ljd.ast.builder.build(prototype)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 28, in build
    return _build_function_definition(prototype)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 49, in _build_function_definition
    node.statements.contents = _build_function_blocks(state, instructions)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 71, in _build_function_blocks
    _establish_warps(state, instructions)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 175, in _establish_warps
    block.warp, shift = _build_warp(state, block.last_address, warp)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 198, in _build_warp
    return _build_numeric_loop_warp(state, last_addr, last)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 318, in _build_numeric_loop_warp
    warp.body = state._warp_in_block(destination)
  File "D:\Users\Bluetiger\Downloads\dataS\scripts\ljd-master\ljd\ast\builder.py
", line 22, in _warp_in_block
    block = self.block_starts[addr]
KeyError: -31379

**Comment by jjdredd** [comment]
Odd, I haven't encountered any bugs in the builder itself! Are you decompiling stripped bytecode?
It could be a good idea to share the .luac file itself.

**Comment by NightNord** [comment]
IIRC FS15 uses luajit 3.0 which may have different bytecode, though I haven't found any specifications for it...

**Comment by Bluetiger** [comment]
I don't think it is stripped. link to one file: http://www.team-sub7.com/download/ls15/main.luc
That is a usefull information, that luajit 3.0 is used. I'll try to find some specification.
I think hundrets of modders would be very glad for the readable scripts.

спаси́бо

**Comment by Bluetiger** [comment]
okay i found something about giants/fs15.

Low-overhead profiling

GIANTS Software GmbH has sponsored the development of a low-overhead profiling functionality for LuaJIT 2.1 in June 2013. GIANTS Software develops a variety of simulation games for desktop, mobile and consoles. These games make extensive use of Lua for scripting and modding. Switching to LuaJIT was instrumental in reducing the CPU load and sustaining the required frame rates on all platforms.

**Comment by jjdredd** [comment]
So some closed-source version of luajit was used, right?

**Comment by jjdredd** [comment]
main.luc file header provided by @Bluetiger indicates that it's luajit 2.1

**Comment by jjdredd** [comment]
looks like we have a few new opcodes:
```
diff --git a/src/lj_bc.h b/src/lj_bc.h
index 7436fab..64c1bcd 100644
--- a/src/lj_bc.h
+++ b/src/lj_bc.h
@@ -89,6 +89,8 @@
   _(ISFC,      dst,    ___,    var,    ___) \
   _(IST,       ___,    ___,    var,    ___) \
   _(ISF,       ___,    ___,    var,    ___) \
+  _(ISTYPE,    var,    ___,    lit,    ___) \
+  _(ISNUM,     var,    ___,    lit,    ___) \
   \
   /* Unary ops. */ \
   _(MOV,       dst,    ___,    var,    ___) \
@@ -143,10 +145,12 @@
   _(TGETV,     dst,    var,    var,    index) \
   _(TGETS,     dst,    var,    str,    index) \
   _(TGETB,     dst,    var,    lit,    index) \
+  _(TGETR,     dst,    var,    var,    index) \
   _(TSETV,     var,    var,    var,    newindex) \
   _(TSETS,     var,    var,    str,    newindex) \
   _(TSETB,     var,    var,    lit,    newindex) \
   _(TSETM,     base,   ___,    num,    newindex) \
+  _(TSETR,     var,    var,    var,    newindex) \
   \
   /* Calls and vararg handling. T = tail call. */ \
   _(CALLM,     base,   lit,    lit,    call) \
```

**Comment by Bluetiger** [comment]
So far I could figure out, is that luajit 3.0 is not ready. there is an article in the wiki from luajit project, which they write about the garbage collector from luajit 3.0 that is everthing so far.

back to fs15. is there a possibility get it to work? I 'm not familiar with Python , and certainly not with this kind of programming . I 'm more with databases and program extensions, programming in C#, C++, Delphi, Cobol and so on.
I can upload the whole bytecode scripts if you wish.

**Comment by jjdredd** [comment]
Adding new instructions to the ljd parser is not complicated. The hard thing is rechecking header format and adding those instructions for use in ast builder and unwarper. In addition to that the decompiler seems to have severe bugs not related to luajit version >= 2.1.

**Comment by NightNord** [comment]
If only these opcodes are added then unwarper shouldn't be the problem. Builder is rather straightforward. But things other than that may have changed (like goto/continue added) - that might be a problem, really.

I've got a number of requests via mail recently with something simulator using luajit 3.0 alpha (these guys are crazy). It seems I've mistaken. Sorry for the confusion.

Well, I'll try to look into adding the new opcodes in a few days. Hopefully it will just work after that, but probably it will not.

**Comment by jjdredd** [comment]
How are you planning to add new opcodes without description? The only way I see is to compile a bunch of code, seek for those opcodes in bytecode dump and try to guess what do these opcodes do.

Another option is to add these opcodes to the parser alone. This way we can parse it correctly but won't be able to decompile. Anyway if you don't have time I could try to make a patch for this.

**Comment by NightNord** [comment]
By looking into the source. And the source tells me that these instructions are not implemented. At least, they are not parsed. So the only problem is that opcode numbers were changed.

But we can't just add them into the parser - it will break all 2.0 scripts. We need to add some special luajit-2.1-only tag and skip such instructions if a bytecode version is 2.9.

**Comment by jjdredd** [comment]
I have added those 4 instructions into instructions.py. Still getting an error in builder (a different error, not the one mentioned by @Bluetiger ).

This is odd because the new instructions aren't used (at least in the file provided by @Bluetiger ), so the only thing that has changed is the instruction numbers.

**Comment by Bluetiger** [comment]
Is it like it Sounds? A light on horizon?

**Comment by jjdredd** [comment]
@Bluetiger , well, I ran it on your main.luc and got something that looked like lua source. You may try
it yourself on other files (branch "ljv2.1" on my fork, though it doesn't include tiny yet important imho fixes yet I've made on the branch "bugfix").

There is much work to be done on the slotworks and unwarper itself!

**Comment by Bluetiger** [comment]
I've tested it on all my luc's. Excellent work so far. Just 22 files won't decompile from over 500. The source code in the other files is looks like what i've expected.
Most of the 22 files seems to have a problem with unwarper, except three files. Could you have a look at it?

http://www.team-sub7.com/download/ls15/CreditsScreen.luc
http://www.team-sub7.com/download/ls15/InputBinding.luc
http://www.team-sub7.com/download/ls15/Utils.luc

(file with unwarper errors)
http://www.team-sub7.com/download/ls15/Vehicle.luc

**Comment by jjdredd** [comment]
Beware! Although you're getting readable lua source, it could be incorrect!

As for the new files, I think they aren't stripped, so I have no Idea what could be wrong.

**Comment by Bluetiger** [comment]
I know. But for the most things it is okay, to know what is the script doing, how the mehtods are used, which methods are there and which variables have to set and so on.

It would be great to get some of this files to readable lua source, because in them is very usefull and needed code to know (files like Utils.luc, Vehicle.luc...). 

But sofar, i look forward with my work in scripting for Simulator. I am very glad for your help.

**Comment by KITT3000** [comment]
I wrote about the NightNord decompiler to version 2.1, but unfortunately without asking for documentation:
"It should work fine for 2.0.3 format, but not for 2.1.0 - it's bytecode is not supported. Probably just because the version has changed (they've added a bunch of new features like GOTO. Probably some new instructions too). But I haven't yet looked into that and I'm unable to find any particular info about the new bytecode instructions.

If you have a link that would be greatly appreciated."

Unfortunately, nowhere to be found these records, I found the link, but it does transfer to the main page: 
http://wiki.luajit.org/Home (section LuaJIT Development)

Can any of you provide your decompiler, as well a few months I am looking for how to decompile the script of this game?

**Comment by lollogamer95** [comment]
HI,i'm a Italian guy

I have started a project of a remastered of the game "Fs15" u can found my project in my

**Comment by jjdredd** [comment]
Decrypting or decompiling? Anyway, the decompiler is not working atm and probably abandoned at least temporarily.

**Comment by joskuijpers** [comment]
Hi! Is there any news about decompiling the luajit luc files from FS15 or 17?
