### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by whklhh** [NightNord/ljd#21]
用@zzwl改过的版本反编译
PS F:\ctf\njupt\ljd-master> py -3 .\main.py .\rua_decode.lua
Traceback (most recent call last):
  File ".\main.py", line 126, in <module>
    retval = main()
  File ".\main.py", line 86, in main
    ast = ljd.ast.builder.build(prototype)
  File "F:\ctf\njupt\ljd-master\ljd\ast\builder.py", line 30, in build
    return _build_function_definition(prototype)
  File "F:\ctf\njupt\ljd-master\ljd\ast\builder.py", line 52, in _build_function_definition
    node.statements.contents = _build_function_blocks(state, instructions)
  File "F:\ctf\njupt\ljd-master\ljd\ast\builder.py", line 74, in _build_function_blocks
    _establish_warps(state, instructions)
  File "F:\ctf\njupt\ljd-master\ljd\ast\builder.py", line 179, in _establish_warps
    block.warp, shift = _build_warp(state, block.last_address, warp)
  File "F:\ctf\njupt\ljd-master\ljd\ast\builder.py", line 192, in _build_warp
    last = instructions[-1]
IndexError: list index out of range

打了一下log：block的first_address和last_address分别是1和-32756，于是传进去的instructions是空的
请问是什么问题呢_(:з」∠)_该怎么改？
样本：https://pan.baidu.com/s/16bvmqNFnFUqVDy78hH5W5A

**Comment by oxpy** [comment]
楼主解决了吗？这个问题，
